### ISSUE TITLE
npm start does work on heroku

### ISSUE THREAD

**Issue by kiddhustle** [uktrade/great-pattern-library#32]
will have to investigat with:

@dahfool @TheUKDave

**Comment by dahfool** [comment]
@kiddhustle This should be fixed now.

**Comment by kiddhustle** [comment]
@dahfool this fix actually causes my manual deployments to PAAS/cloud foundry to fail for some reason (not sure why PAAS is running the heroku command automatically)

Did you know why gulp could not be found from the relative path ```./node_modules/.bin/gulp``` on heroku

**Comment by dahfool** [comment]
@kiddhustle don't know why PAAS/cloud is running heroku `heroku-prebuild` command.
`./node_modules/.bin/gulp` was not running because the dependency was missing, `npm install` was not ran.

**Comment by dahfool** [comment]
@kiddhustle i think we resolve this issue, i will close.
